### ISSUE TITLE
IP Address difficult to enter IP

### ISSUE THREAD

**Issue by SokolovRobert** [JacobAMason/Velocity-Vortex-Scorekeeper#1]
Field input is set as "number" input, and makes it's impossible to enter a port # on certain keyboards

**Comment by JacobAMason** [comment]
Port is hardcoded to 3486 to make entry easier.

**Comment by SokolovRobert** [comment]
My phone can't seem to find the server - might need help with this :(

**Comment by JacobAMason** [comment]
Virtual or physical phone?

**Comment by SokolovRobert** [comment]
Physical - used the APK from the repo and have it sitting on my WiFi with the computer running the server. Haven't built the APK from source yet.

**Comment by JacobAMason** [comment]
Might want to do it from source. I'm not sure how old that apk is

**Comment by SokolovRobert** [comment]
Build from source works :+1:

**Comment by JacobAMason** [comment]
Okay. I'll need to upload a new release.
